export const FaucetAbi = [
    {
       "inputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "inputs":[
          
       ],
       "name":"AccessControlBadConfirmation",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          },
          {
             "internalType":"bytes32",
             "name":"neededRole",
             "type":"bytes32"
          }
       ],
       "name":"AccessControlUnauthorizedAccount",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"IMonadexV1Faucet__InvalidFaucet",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"IMonadexV1Faucet__InvalidFaucetCreationParams",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"IMonadexV1Faucet__InvalidFaucetUpdateParams",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"IMonadexV1Faucet__NotEligibleToCollectFromFaucet",
       "type":"error"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"by",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"receiver",
             "type":"address"
          }
       ],
       "name":"CollectedTokensFromFaucet",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"by",
             "type":"address"
          },
          {
             "components":[
                {
                   "internalType":"string",
                   "name":"tokenName",
                   "type":"string"
                },
                {
                   "internalType":"string",
                   "name":"tokenSymbol",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"decimals",
                   "type":"uint256"
                },
                {
                   "internalType":"string",
                   "name":"uri",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"interval",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountToEmitAtEachInterval",
                   "type":"uint256"
                }
             ],
             "indexed":true,
             "internalType":"struct IMonadexV1Faucet.FaucetDetails",
             "name":"faucetDetails",
             "type":"tuple"
          }
       ],
       "name":"FaucetCreated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"by",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"newInterval",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"newAmountToCollectEachInterval",
             "type":"uint256"
          }
       ],
       "name":"FaucetUpdated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"previousAdminRole",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"newAdminRole",
             "type":"bytes32"
          }
       ],
       "name":"RoleAdminChanged",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"account",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          }
       ],
       "name":"RoleGranted",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"account",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          }
       ],
       "name":"RoleRevoked",
       "type":"event"
    },
    {
       "inputs":[
          
       ],
       "name":"DEFAULT_ADMIN_ROLE",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"FAUCET_MANAGER_ROLE",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_token",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_to",
             "type":"address"
          }
       ],
       "name":"collectTokensFromFaucet",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"string",
                   "name":"tokenName",
                   "type":"string"
                },
                {
                   "internalType":"string",
                   "name":"tokenSymbol",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"decimals",
                   "type":"uint256"
                },
                {
                   "internalType":"string",
                   "name":"uri",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"interval",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountToEmitAtEachInterval",
                   "type":"uint256"
                }
             ],
             "internalType":"struct IMonadexV1Faucet.FaucetDetails",
             "name":"_faucetDetails",
             "type":"tuple"
          }
       ],
       "name":"createFaucet",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"getAllTokens",
       "outputs":[
          {
             "internalType":"address[]",
             "name":"",
             "type":"address[]"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_token",
             "type":"address"
          }
       ],
       "name":"getFaucetDetails",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"string",
                   "name":"tokenName",
                   "type":"string"
                },
                {
                   "internalType":"string",
                   "name":"tokenSymbol",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"decimals",
                   "type":"uint256"
                },
                {
                   "internalType":"string",
                   "name":"uri",
                   "type":"string"
                },
                {
                   "internalType":"uint256",
                   "name":"interval",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountToEmitAtEachInterval",
                   "type":"uint256"
                }
             ],
             "internalType":"struct IMonadexV1Faucet.FaucetDetails",
             "name":"",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          }
       ],
       "name":"getRoleAdmin",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"grantRole",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"hasRole",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_user",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_token",
             "type":"address"
          }
       ],
       "name":"isEligibleToCollect",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"callerConfirmation",
             "type":"address"
          }
       ],
       "name":"renounceRole",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"revokeRole",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes4",
             "name":"interfaceId",
             "type":"bytes4"
          }
       ],
       "name":"supportsInterface",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_interval",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amountToEmitAtEachInterval",
             "type":"uint256"
          }
       ],
       "name":"updateFaucet",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]